/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  referenceId: string | null;
  tenantId: string;
  type: string;
}

export interface AuditLog {
  action: string;
  afterValue: Json | null;
  beforeValue: Json | null;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  module: string;
  tenantId: string;
  userId: string | null;
}

export interface CourierLedgerEntries {
  amount: Numeric;
  balanceAfter: Numeric;
  courierId: string;
  createdAt: Generated<Timestamp>;
  entryType: string;
  id: Generated<string>;
  orderId: string | null;
  tenantId: string;
  voucherId: string | null;
}

export interface CourierRemittanceBatches {
  amount: Numeric;
  batchNumber: string;
  courierId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  status: Generated<string>;
  tenantId: string;
  voucherId: string | null;
}

export interface CourierRemittanceOrders {
  orderId: string;
  remittanceBatchId: string;
  remittedAmount: Numeric | null;
  slipAmount: Numeric;
}

export interface Couriers {
  commissionFlat: Generated<Numeric | null>;
  commissionPercent: Generated<Numeric | null>;
  contact: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  mode: Generated<string>;
  name: string;
  remittanceCycleDays: Generated<number>;
  tenantId: string;
}

export interface Customers {
  address: string | null;
  city: string | null;
  createdAt: Generated<Timestamp>;
  firstOrderAt: Timestamp | null;
  id: Generated<string>;
  name: string;
  phone: string;
  tenantId: string;
}

export interface Employees {
  advanceBalance: Generated<Numeric>;
  baseSalary: Numeric | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  role: string | null;
  status: Generated<string>;
  tenantId: string;
  userId: string | null;
}

export interface IntegrationCredentials {
  createdAt: Generated<Timestamp>;
  credentialsEncrypted: Buffer | null;
  id: Generated<string>;
  lastError: string | null;
  lastSyncAt: Timestamp | null;
  provider: string;
  status: Generated<string>;
  storeUrl: string | null;
  syncFrequencyMinutes: Generated<number | null>;
  tenantId: string;
}

export interface SyncLogs {
  createdAt: Generated<Timestamp>;
  error: string | null;
  finishedAt: Timestamp;
  id: Generated<string>;
  ok: boolean;
  provider: string;
  startedAt: Timestamp;
  summary: Json | null;
  syncType: string;
  tenantId: string;
  trigger: string;
}

export interface Locations {
  address: string | null;
  id: Generated<string>;
  isDefault: Generated<boolean>;
  name: string;
  tenantId: string;
}

export interface OrderItems {
  id: Generated<string>;
  orderId: string;
  qty: number;
  unitCost: Numeric;
  unitPrice: Numeric;
  variantId: string;
}

export interface Orders {
  courierId: string | null;
  createdAt: Generated<Timestamp>;
  customerId: string;
  deliveredAt: Timestamp | null;
  dispatchedAt: Timestamp | null;
  id: Generated<string>;
  inventoryDeducted: Generated<boolean>;
  orderNumber: string;
  packedAt: Timestamp | null;
  paymentType: string;
  placedAt: Generated<Timestamp>;
  remarks: string | null;
  returnedAt: Timestamp | null;
  source: Generated<string>;
  status: Generated<string>;
  tenantId: string;
  trackingNumber: string | null;
}

export interface PdfImports {
  courierId: string | null;
  createdAt: Generated<Timestamp>;
  fileName: string;
  id: Generated<string>;
  importedBy: string | null;
  ordersMatched: Generated<number>;
  ordersTotal: Generated<number>;
  status: Generated<string>;
  tenantId: string;
}

export interface Permissions {
  canApprove: Generated<boolean>;
  canCreate: Generated<boolean>;
  canDelete: Generated<boolean>;
  canEdit: Generated<boolean>;
  canView: Generated<boolean>;
  id: Generated<string>;
  module: string;
  roleId: string;
}

export interface Products {
  channel: Generated<string>;
  countryOfOrigin: string | null;
  createdAt: Generated<Timestamp>;
  handle: string;
  id: Generated<string>;
  imageUrl: string | null;
  option1Name: Generated<string | null>;
  option2Name: Generated<string | null>;
  option3Name: string | null;
  status: Generated<string>;
  tenantId: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface PurchaseOrderLines {
  costPrice: Numeric;
  id: Generated<string>;
  purchaseOrderId: string;
  qtyOrdered: number;
  qtyReceived: Generated<number>;
  variantId: string;
}

export interface PurchaseOrders {
  id: Generated<string>;
  orderedAt: Generated<Timestamp>;
  receivedAt: Timestamp | null;
  status: Generated<string>;
  tenantId: string;
  vendorId: string;
}

export interface Roles {
  clonedFrom: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isCustom: Generated<boolean>;
  name: string;
  tenantId: string;
}

export interface SchemaMigrations {
  appliedAt: Generated<Timestamp>;
  filename: string;
}

export interface StockAdjustments {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  note: string | null;
  qtyDelta: number;
  reasonCode: string;
  tenantId: string;
  userId: string;
  variantId: string;
}

export interface Tenants {
  address: string | null;
  businessName: string;
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  id: Generated<string>;
  logoUrl: string | null;
  orderNumberPrefix: Generated<string | null>;
  taxRatePercent: Numeric | null;
  timezone: Generated<string>;
  voucherNumberPrefix: Generated<string | null>;
}

export interface Users {
  deactivatedAt: Timestamp | null;
  email: string;
  id: Generated<string>;
  invitedAt: Generated<Timestamp>;
  lastLoginAt: Timestamp | null;
  name: string;
  passwordHash: string;
  phone: string | null;
  roleId: string;
  status: Generated<string>;
  tenantId: string;
  twoFaEnabled: Generated<boolean>;
  twoFaMethod: string | null;
}

export interface Variants {
  binName: string | null;
  costPrice: Numeric | null;
  createdAt: Generated<Timestamp>;
  hsCode: string | null;
  id: Generated<string>;
  locationId: string | null;
  onHand: Generated<number>;
  option1Value: string | null;
  option2Value: string | null;
  option3Value: string | null;
  productId: string;
  reorderLevel: Generated<number>;
  reserved: Generated<number>;
  salePrice: Numeric | null;
  sku: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Vendors {
  contact: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  status: Generated<string>;
  tenantId: string;
}

export interface Vouchers {
  amount: Numeric;
  attachmentUrl: string | null;
  createdAt: Generated<Timestamp>;
  creditAccountId: string;
  debitAccountId: string;
  enteredBy: string;
  id: Generated<string>;
  photoData: Buffer | null;
  photoMimeType: string | null;
  reference: string | null;
  tenantId: string;
  totalUnits: Numeric | null;
  unitType: string | null;
  vendorVoucherNumber: string | null;
  voucherDate: Timestamp;
  voucherNumber: string;
  voucherType: string;
}

export interface DB {
  accounts: Accounts;
  auditLog: AuditLog;
  courierLedgerEntries: CourierLedgerEntries;
  courierRemittanceBatches: CourierRemittanceBatches;
  courierRemittanceOrders: CourierRemittanceOrders;
  couriers: Couriers;
  customers: Customers;
  employees: Employees;
  integrationCredentials: IntegrationCredentials;
  locations: Locations;
  orderItems: OrderItems;
  orders: Orders;
  pdfImports: PdfImports;
  permissions: Permissions;
  products: Products;
  purchaseOrderLines: PurchaseOrderLines;
  purchaseOrders: PurchaseOrders;
  roles: Roles;
  schemaMigrations: SchemaMigrations;
  stockAdjustments: StockAdjustments;
  syncLogs: SyncLogs;
  tenants: Tenants;
  users: Users;
  variants: Variants;
  vendors: Vendors;
  vouchers: Vouchers;
}
